### PR TITLE
Plates v1.0.0

### PR DESCRIPTION
**Pull request by Southern**
Plates has been pretty abused over the past year. It's time that it got some love! We've been rebuilding it from the ground up. Here are some of the things that this recode aims to fix, or has already fixed:
- Accept multiple HTML strings, maps, collections, and data in `Plates.bind`
- Have a parser that is accessible from Plates, but not dependent on being used in Plates.
- Make code more manageable.
- Better parsing of HTML for manipulating tags:
  - Use regular expressions for parsing rather than [iterating through each character](https://github.com/flatiron/plates/blob/master/lib/plates.js#L247-L451).
  - Fix mapping to where things such as `.append` actually append, rather than overwriting all of the HTML in the tag.

This code is currently incomplete, no tests are currently provided, and any of the methods in this code could change at any time. There will be completely new documentation, once the code is complete, that will outline all of the methods that are available in the actual release.

Pull requests are welcome if you would like to contribute to this code.

### CODE REVIEW

**Comment by davidchase** [comment]
@Southern @3rd-Eden curious on the status of this PR, let alone project... is it abandoned ?

**Comment by serapath** [comment]
same question. i forked plates.js several months ago and took some time to go through all the commits on this project to include them in my fork, just to realize, that they were only commit to polish stuff.
(e.g. spelling fixes, code formatting, readme updates, etc...)

Basically the project as is works for me, but i wonder if the code could be made smaller and maybe there is room for performance optimization.
If the contributors decided to move on - because they do not consider plates to be any longer "state of the art" for whatever reason, it would be nice to learn about that.

thx :-)

**Comment by 3rd-Eden** [comment]
@davidchase In case of this pull request it cannot and will not be merged in until all points expressed above are addressed. In addition to that the usage of this module has been declining at Nodejitsu as we've found it quite hard and super annoying to maintain template's rendering process in two different locations. So I would say, we welcome new contributors that want to help out with maintaining and moving this project forward.

**Comment by davidchase** [comment]
@3rd-Eden is there another module you guys use at Nodejitsu instead of this one?

**Comment by jcrugzz** [comment]
@davidchase check out https://github.com/bigpipe/, https://github.com/nodejitsu/contour and https://github.com/nodejitsu/browsenpm.org for an idea of what we are working with these days.

**Comment by davidchase** [comment]
@jcrugzz those are all excellent modules but I was hoping for something similar to plates... I really was drawn to the dsl free lack of `{{}}` templates.. we use handlebars currently and before used jade, etc but plates had me interested but it doesn't seem like a project that is being actively maintained.. unless you would still recommend its use in production? It seems like a lot of people try develop these dsl free templates modules but they either don't catch on or something else happens and seems like people go back to whats known such as handlebars or something similar. I might have to be another one to make an attempt or contribute to something like this or [hyperglue](https://github.com/substack/hyperglue) & [hyperstream](https://github.com/substack/hyperstream). :neutral_face:

**Comment by serapath** [comment]
I'm pretty attracted to "programmatic template systems" _(that's what they are called in [a blog post from strongloop](http://strongloop.com/strongblog/template-systems-in-node/))_

For example:
- https://github.com/flatiron/plates
- https://github.com/medikoo/domjs
- https://github.com/substack/hyperglue

I always thought, with those templating language, it should be easy to do live content updates "data binding", because the tags tell me exactly where to update the data.

This could be combined with `requestAnimationFrame` and libraries like `fastdom` to optimize performance or on the server side just by using plates.

I'm not so familiar with the virtual DOM concept and what else might be necessary to optimize performance - but i imagine, that i could get a pretty nice templating solution with this approach.

I actually wonder why nobody tried to go down that route yet - or if somebody did - i'm always happy to learn about cool projects :-)
If somebody could point me towards potential flaws in the concept, that would be equally nice, so that i don't try something stupid.

**Comment by 3rd-Eden** [comment]
@davidchase As we've moved completely away from this pattern, we're using nothing else like this. The modules that we use are the once's that @jcrugzz mentioned. Our BigPipe system allows each layout component to be written in different template language if people want to do so, we're currently using `html`, `handlebars`, `jade` and `ejs` using this system (template magic is powered by https://github.com/bigpipe/temper).

@serapath Sure, it's easy to update content using data binding but the problem starts when you need to work your layout and start moving elements which causes everything to break as your mapping is no longer up to date. This requires you to edit other files which contains these mappings which is becoming an increasing burden for more complex layouts.

"virtual dom" wouldn't really yield any major benefits on the server as there isn't any new DOM that needs to be repainted. You are just manipulating in memory objects with function calls.

**Comment by serapath** [comment]
Can you elaborate what you mean?
For example, on this [codepen](http://codepen.io/anon/pen/vEeXyg), you can click the first element and it alerts something. Afterwards you drag it around and it gets clicked, it alerts the same stuff, thus the event listener still works.

What is the problem about re-positioning?

**Comment by indexzero** [comment]
Closing this due to age. This project is formally deprecated. Will be adding a notice soon.

**Pull request closed without merging**
